# Generated by Django 6.0.6 on 2026-08-13 19:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0007_alter_perfilusuario_options_alter_perfilusuario_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRecuperacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacion', to='dashboard.cliente')),
            ],
            options={
                'verbose_name': 'Token de recuperación (Cliente)',
                'verbose_name_plural': 'Tokens de recuperación (Clientes)',
                'db_table': 'token_recuperacion_cliente',
                'ordering': ['-creado'],
            },
        ),
    ]
