# Generated by Django 4.2.30 on 2026-06-04 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_inventario_options_pedido_notas_producto_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={},
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.rol'),
        ),
        migrations.AlterModelTable(
            name='perfilusuario',
            table=None,
        ),
    ]
