# Generated by Django 4.2.30 on 2026-08-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_perfilusuario_options_alter_perfilusuario_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disenador',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
