# Generated by Django 5.1.15 on 2026-09-04 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_disenador_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(default='Haze Studios', max_length=120)),
                ('tipo', models.CharField(choices=[('notificacion_pedido', 'Notificación de Pedido'), ('informativo', 'Informativo'), ('promocional', 'Promocional'), ('soporte', 'Soporte')], default='notificacion_pedido', max_length=30)),
                ('contenido', models.CharField(help_text='Contenido del mensaje (máximo 500 caracteres)', max_length=500)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('entregado', 'Entregado'), ('leido', 'Leído'), ('fallido', 'Fallido')], default='enviado', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(db_column='id_destinatario', help_text='Usuario destinatario del mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='dashboard.cliente')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_enviados', to='dashboard.pedido')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'mensajes',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
