# Generated by Django 5.1.15 on 2026-09-04 02:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='contenido',
            field=models.CharField(help_text='Contenido del mensaje (máximo 500 caracteres)', max_length=500, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
