# Generated by Django 5.1.15 on 2026-09-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='disenador',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
    ]
