# Generated by Django 5.1.15 on 2026-09-08 23:24

from django.db import migrations


def crear_permiso_y_asignar(apps, schema_editor):
    Permiso = apps.get_model('dashboard', 'Permiso')
    Rol = apps.get_model('dashboard', 'Rol')

    permiso, _ = Permiso.objects.get_or_create(
        codigo='acceso_dashboard',
        defaults={
            'nombre': 'Acceso al Panel de Administración',
            'descripcion': 'Permite entrar al dashboard/administración.',
        }
    )

    rol_admin, _ = Rol.objects.get_or_create(nombre='admin')
    rol_admin.permisos.add(permiso)


def revertir(apps, schema_editor):
    Permiso = apps.get_model('dashboard', 'Permiso')
    Permiso.objects.filter(codigo='acceso_dashboard').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0014_pedido_fecha_creacion_alter_pedido_estado'),
    ]

    operations = [
        migrations.RunPython(crear_permiso_y_asignar, revertir),
    ]
